#!/bin/bash

#DESCRIPTION: Setting Lo DPI Scaling Factor 

# ensure running as root, if not, sudo and execute script again
if [ "$(id -u)" != "0" ]; then
  exec sudo "$0" "$@"
fi

SCRIPTPATH=$(dirname $(readlink -f $0))

echoError() {
  RED='\033[0;31m'
  NC='\033[0m' # No Color
  printf "${RED}[!]${NC} $1\n"
}
echoInfo() {
  YELLOW='\033[0;33m'
  NC='\033[0m' # No Color
  printf "${YELLOW}[i]${NC} $1\n"
}
echoAction() {
  GREEN='\033[0;32m'
  NC='\033[0m' # No Color
  printf "${GREEN}[+]${NC} $1\n"
}
echoSection() {
  CYAN='\033[0;36m'
  NC='\033[0m' # No Color
  printf "${CYAN}$1${NC}\n"
}


echoAction "Setting low DPI Scaling Factor - Please logout and login again!"
WMver=$(echo "$XDG_DATA_DIRS" | grep -Eo 'xfce|kde|gnome')

if [ $WMver == "xfce" ]; then
    echoInfo "This is XFCE"
    xfconf-query -c xsettings -p /Gdk/WindowScalingFactor -s 1 -n -t int
    xfconf-query -c xfwm4 -p /general/theme -s Kali-Dark
    xfconf-query -c xsettings -p /Gtk/CursorThemeSize -s 22 -n -t int
  
  elif [ $WMver == "gnome" ]; then
    echoInfo "This is GNOME"
    gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "[{'Gdk/WindowScalingFactor', <1>}]"
	  gsettings set org.gnome.desktop.interface scaling-factor 1
    
  elif [ $WMver == "KDE" ]; then
    echoInfo "LODPI changes are not implemented for KDE"
  
  else
  	echoError "Window Manager could not be detected!"  
    
fi
