#!/bin/bash
#DESCRIPTION: Enable logging and recording (persistently)

# # ensure running as root, if not, sudo and execute script again
# if [ "$(id -u)" != "0" ]; then
#   exec sudo "$0" "$@"
# fi

install_path="/usr/share/kalima"
user_path="$HOME/.config/kalima"

# Print helpers
print_newline() {
  printf "\n"
}

print_verbose()
{
  echo "$@" >&3
}

print_section()
{
  printf "\e[36m    %s\e[0m\n" "$@"
}

print_action()
{
  printf "\e[32m[+]\e[0m %s\n" "$@"
}

print_error()
{
  printf "\e[31m[!]\e[0m %s\n" "$@"
}

print_info()
{
  printf "\e[33m[i]\e[0m %s\n" "$@"
}

function usage () {                                      
  echo -e "Kalima Recorder - Do it like the spies do!

  Usage: $0 -e | -d [--help]

    -e    Enable logging on new terminals
    -d    Disable logging on new terminals

  Note:
  * While logging new terminal prompts will have a \033[0;31m\u229A\033[0m leftmost
  * All logs are stored under \"$(cat $install_path/project_home)/1_evidence/\"
  * Close your terminals and open them again via the desktop shortcut, or 
  * Use \"/usr/local/bin/kalima terminal\" from the command line.
  
  Replay:
  * Use \"asciinema play terminal_{date}_{time}.cast\" to replay as a movie
  * Use \"asciinema cat terminal_{date}_{time}.cast\" to view as a file

"
exit 1
}


while getopts "ed" options; do                              
  case "${options}" in                         
    e)                                         
      print_action "Enabling logging for new terminal sessions..."
      echo "true" > "$user_path/record_session"            
      ;;
    d )                                        
      print_action "Disabling logging for new terminal sessions..."
      echo "false" > "$user_path/record_session"
      ;;
    : )                                         
      print_error "-${OPTARG} requires an argument."
      usage
                        
      ;;
    \? )                                       
      usage
                     
      ;;
  esac
done


[ $OPTIND -eq 1 ] && usage
